{% set name = "glow" %}
{% set pypi_name = "glow.py" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: 9993d8dd2552314e522b3777715b98fc5a34ba5126861cd6f0bb4eecd1a18940

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.7
    - pyspark >=2.4.0
    - nptyping >=1.3.0
    - numpy >=1.18.1
    - opt_einsum >=3.2.0
    - pandas >=1.0.1
    - statsmodels >=0.10.0
    - typeguard >=2.9.1

test:
  imports:
    - glow
    - glow.gwas
    - glow.wgr

about:
  home: https://projectglow.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: An open-source toolkit for large-scale genomic analysis
  description: |
    Glow is an open-source toolkit for working with genomic data at 
    biobank-scale and beyond. The toolkit is natively built on Apache Spark, 
    the leading unified engine for big data processing and machine learning, 
    enabling the scale of the cloud for genomics workflows.
  doc_url: https://glow.readthedocs.io/
  dev_url: https://github.com/projectglow/glow

extra:
  recipe-maintainers:
    - henrydavidge
    - karenfeng
    - kianfar77
